### PR TITLE
[Done] wheels: Add Python 3.10 and GEOS 3.10.0

### PR DESCRIPTION
**Pull request by caspervdw**
As discussed in #414 , this also drops support for GEOS<=3.6 and Python 3.6.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is this required for a 0.12 release? Things are working, so I would say that we could also release keeping those version support to have a last release for them, and only afterwards drop them?

I would also prefer to first check that the other Shapely devs are on the same page. I don't expect any problems, but I also don't want to create new blockers for starting to integrate the pygeos code into the shapely repo (now there is a maintenance branch for 1.8, I hope to do that soon)

**Comment by caspervdw** [comment]
Right, it might be a bit rash to drop the support of the older versions. Ubuntu 18 for instance ships with GEOS 3.6 and Python 3.6.

I do like to have the wheels for py 3.10 in the matrix already.

**Comment by jorisvandenbossche** [comment]
> I do like to have the wheels for py 3.10 in the matrix already.

Yes, that part would certainly be nice

**Comment by jorisvandenbossche** [comment]
And I also +1 on using GEOS 3.10 for the wheels, to be clear

**Comment by caspervdw** [comment]
I reverted the changes and kept only the GEOS 3.10.0 and Python 3.10 addition.
Should be good for a release after this is merged.

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Comment by caspervdw** [comment]
The 64-bit build seems to end up in lib64 as of GEOS 3.10.0. Might be caused by https://github.com/libgeos/geos/pull/447.

Our script expects the libraries in lib. I am not used to working with cmake— @mwtoews could you give me a hint how to proceed?

**Comment by mwtoews** [comment]
Use `-D CMAKE_INSTALL_LIBDIR=lib` as is done for conda [here](https://github.com/conda-forge/geos-feedstock/blob/master/recipe/build.sh).

**Comment by caspervdw** [comment]
> Use `-D CMAKE_INSTALL_LIBDIR=lib` as is done for conda [here](https://github.com/conda-forge/geos-feedstock/blob/master/recipe/build.sh).

Thanks @mwtoews this saved me a lot of time going through cmake documentation. The build works, I'll wait for the aarch64 to complete and then we can merge & release.

**Pull request merged**
