### PR TITLE
WIP: add subdivide function in Cython

### LINKED ISSUE #244: Proposed: Port ST_Subdivide from PostGIS
[ST_Subdivide](https://postgis.net/docs/ST_Subdivide.html) divides complex geometries into smaller rectangular chunks of relatively similar vertex counts, which are then much better to use in spatial indexing, predicate, and related functions.  The algorithm works by recursively cutting geometries along one dimension then the other.

This is not strictly about exposing GEOS internals to Python, so it might not be a good fit here.  But given the recent work with Cython and strong dependence on internals here, it might be a worthwhile experiment (plus, I need this for one of my projects).  

Unless there was opposition, I am hoping to try and implement this within Cython here.

### PR DESCRIPTION
**Pull request by brendan-ward**
Resolves #244 

This adds an adaption of the algorithm in ST_Subdivide.  It recursively subdivides an ndarray until reaching a target number of vertices.  It uses a quad tile approach vs horizontal or vertical slice (whichever is longer in a given step) as used in ST_Subdivide.  Haven't yet tested which has better performance, but there is a benchmark here so we can track that.

This includes some minor changes I need to backport to #247 around the C vectors.

The actual subdivide function itself is not that complex, but this involved adding a lot of supporting code: we needed several GEOS functions in Cython, and needed a few basic utility functions (`_bounds`, `_box`) that we needed here in a way that couldn't reuse the ufuncs (so they can be within `nogil` blocks / functions).

This currently uses GEOS functions availabe in 3.7 and 3.8, which will require an approach worked out in #255 

Some of the biggest additions here, and most complex to work out, were resizeable vectors that were more obvious / easy to use in Cython.  We couldn't use the existing C vector approach as-is for certain functions because we needed to lock in specific type bindings in C rather than in Python.  This then led to either creating type-specific functions for each vector type (e.g., `index_vec_init`, `index_vec_push`, etc), or a mess of original functions like `kv_init` and type specific functions to bind in the type.  It also felt less friendly to use in Cython, and having a context manager to release the vectors seemed like a good idea.

These still need a bit more work, esp. to release `GEOSGeometries` when manually clearing out the `GeometryVector` in case of an error.

### CODE REVIEW

**Comment by brendan-ward** [comment]
Benchmarks for splitting into 4 tiles per recursion vs bisecting longest dimension:
4 tiles:  866±10ms
bisect:  933±20ms

likely highly dependent on the spatial configuration of vertices.  Vertices in the benchmark generated geometries are relatively evenly distributed.

A more optimal approach could use median points rather than means (center x,y) so that there are roughly equal point densities in each quadrant, but there is some overhead to sorting points.  Optimal in this case also depends on how unevenly the points are distributed.

**Comment by jorisvandenbossche** [comment]
Thanks a lot for working on this! 
I didn't yet look at the actual code, but just one remark, or rather concern: this seems to be adding quite some complexity to the cython side (and some duplication of things that are also implemented already in C), which *could* be a sign that this should rather be done in C?  (eg we could say that if you need the resizable vector, that we do such algos in C instead of cython)

(to be clear, I don't have the answer (it might well be that we want this), just noting this is probably something we need to consider / discuss how far we want to go in cython in general)

**Comment by brendan-ward** [comment]
Agreed on the concerns about complexity, and not being sure just how far we want to reimplement things in Cython.

If we kept this in C _and_ modularized some of the shared functions (bounds, box) so that they could be used outside of ufuncs, then that would cut down on reimplementation in Cython a bit.

Most of what is here should port over to C pretty easily; it just involves a bit more overhead (typing effort) to make the function available for use in Python.  I might try that (in a different PR), to see how the two approaches compare.

**Comment by brendan-ward** [comment]
Closing since we did not end up implementing this here; may eventually be implemented in GEOS or Shapely.

**Pull request closed without merging**
