### PR TITLE
[Done] OSX arm64 and universal2 wheels

### PR DESCRIPTION
**Pull request by caspervdw**
Ref #372

### CODE REVIEW

**Comment by caspervdw** [comment]
@reinout I am experimenting with arm64 builds for OSX, but I don’t have a platform to test the builds on. Do you have an opportunity to test the OSX arm64 wheel that is under “artefacts” in the latest github action build?

You should be able to pip install it and then run `pytest --pyargs pygeos.tests`

**Comment by martinfleis** [comment]
@caspervdw I can test it later today.

**Comment by martinfleis** [comment]
Looks okay to me. 

The result using `pygeos-0+untagged.1.g8ddf3d0-cp310-cp310-macosx_11_0_arm64.whl` :

```
=========== 2536 passed, 20 skipped, 22 xpassed, 7 warnings in 2.45s ===========
```

Shall I try all Python versions?

**Comment by caspervdw** [comment]
Thanks @martinfleis, great that it works! It was mainly the arm64 build of GEOS I was worried about, and that is the same for all python versions.

I am planning to also try a “universal2” build (which is arm64 and x86_64 combined). Maybe you can test that as well in due time?

**Comment by martinfleis** [comment]
> I am planning to also try a “universal2” build (which is arm64 and x86_64 combined). Maybe you can test that as well in due time?

Happy to do so, just ping me when ready.

**Comment by caspervdw** [comment]
@martinfleis  I am curious whether the Python 3.8 ARM64 builds work for you.

For Python 3.8, we build against NumPy 1.17.3, while NumPy 1.21.3 is the earliest version that supplies ARM64 wheels. But because we are cross compiling, the x86_64 wheel might suffice. The build didn't error at least, but I am curious if the resulting wheel worked for you.

Either way, we probably can better build against 1.21.3 on Py3.8 (just like we limit the aarch64 builds to >=1.19.3, but we have to do that there because the build requires the numpy aarch64 wheel; with osx arm64 that doesnt seem to be the case)

My latest commit should result in a universal2 build also. But the build will take some time.

**Comment by martinfleis** [comment]
The 3.8 version from the same artifact I downloaded earlier works but pip pulls numpy 1.21 during the installation.

```
(pygeos) martin@Martins-MacBook-Air ~ % pip install /Users/martin/Downloads/artifact/pygeos-0+untagged.1.g8ddf3d0-cp38-cp38-macosx_11_0_arm64.whl
Processing ./Downloads/artifact/pygeos-0+untagged.1.g8ddf3d0-cp38-cp38-macosx_11_0_arm64.whl
Collecting numpy>=1.13
  Downloading numpy-1.21.4-cp38-cp38-macosx_11_0_arm64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 970 kB/s            
Installing collected packages: numpy, pygeos
Successfully installed numpy-1.21.4 pygeos-0+untagged.1.g8ddf3d0
```

**Comment by caspervdw** [comment]
Good to hear. That it pulls 1.21.4 was to be expected. Thanks for testing!

**Comment by caspervdw** [comment]
@martinfleis The build has finished, could you test the universal2 wheel?

**Comment by martinfleis** [comment]
`pygeos-0+untagged.1.gfa5205f-cp38-cp38-macosx_10_9_universal2.whl` seems to work fine!

**Pull request merged**
