### PR TITLE
WIP: get parts of a geometry collection or multi* geometries

### LINKED ISSUE #127: Function to "flatten" or "explode" multi-geometries
For several use cases in geopandas (the explode method, for plotting), it would be useful to have a function that explodes multi-geometries. 

In pseudo-python (and only for an array with only multi-geometries, would of course this needs to be generalized, but for illustration purposes), this could look like:

```
def flatten_multipolygons(arr):
   indices = [] 
   res = [] 
  
   for i, geom in enumerate(arr): 
        for j in range(pygeos.get_num_geometries(geom)): 
            poly = pygeos.get_geometry(geom, j) 
            res.append(poly)
            indices.append(i)
    
   return np.array(res, dtype=object), np.array(indices)
```

(the indices are already possible to calculate based on get_num_geometries(arr))

This is something that could be fairly easily implemented in cython, I think. Although we should check what performance benefit it can give. Thoughts?

Questions are *what* to explode though. MultiPoint/MultiLineString/MultiPolygon would be clear candidates, but GeometryCollection is maybe less clear (what with Multi geoms inside a GeometryCollection ?).

### LINKED ISSUE #128: PROPOSAL: function to return all parts of a multi-geometry as ndarray
Extracting the individual geometries from a multi geometry / collection is a fairly common task.

In shapely this is available using the `geoms` attribute on multi / collection geometry object.

There doesn't appear to be any counterpart in GEOS, nor does there need to be: it gives us the count of parts and an accessor given an index (plus, it would be hard to consume an array of geometries from GEOS).

Right now, we have to do this in a Python loop, e.g.,
```
parts = [pygeos.get_geometry(g, i) for i in range(0, pygeos.get_num_geometries(g))]
```

Which is certainly not optimal for large numbers of geometries.

There are a number of cases where we would also want to do this for all geometries in an ndarray of source geometries.

A standard ufunc approach doesn't work for this, because the output shape is greater than or equal to the input shape.  It also doesn't look like the generalized ufunc expressions get us here either, though I haven't been able to fully get my head around those.  Is there a way to do this as a ufunc?

Instead, I think we could expose a new function implemented in C that provides this functionality.

Given a singular geometry or 1D array_like of geometries, which returns a 1D array of all parts:

```
>>> geom = pg.Geometry("MULTIPOLYGON (((0 0, 0 10, 10 10, 0 0)), ((1 1, 1 10, 10 10, 1 1)))")
>>> parts = pygeos.get_parts(geom)
array([<pygeos.Geometry POLYGON ((0 0, 0 10, 10 10, 0 0))>, <pygeos.Geometry POLYGON ((1 1, 1 10, 10 10, 1 1))>])
```

For the 1D input case, we may want to know the indexes of the input geometry as well as the parts in order to relate back to the inputs (e.g., for other attributes within a DataFrame).  

In that case, we may want to limit `pygeos.get_parts()` to the single geometry case, and provide `pygeos.get_parts_bulk()` (better name welcome!!  Maybe `get_parts_indexed`?) which returns an array of shape (2,n) where the first array is indexes into source and the second is array of geometries.  

This could leverage some of the existing code used in the ufuncs, so the new code here is mostly in wrapping a bit of C as python functions.

### PR DESCRIPTION
**Pull request by brendan-ward**
Closes #127, closes #128 

This includes a bit of refactoring to make it easier to reuse our functions and types in C.

`vector`: types and functions for working with resizable vectors
`geom_op`: arbitrary place to put operations on geometries that are not ufuncs and not at the core of creating / converting geometries

This lifted the `GetGeometryN` from `ufuncs.c` to `geom_op.c` for reusibility in both.  There are a few other C functions in `ufuncs` that could move here as well (to keep the ufunc code focused on ufuncs), but weren't directly related to changes here.

We clearly need a better name for this function, `get_parts` is just a placeholder for now.

This takes as input a geometry or 1d array of geometry, and returns a tuple of indexes and new geometries for the parts.

GeometryCollection is not yet implemented.  There are recursive aspects of that which will require a bit more refactoring here.

I did not implement the single geometry case.  There might be a better way to handle that in a different function or method.

Key things to focus on here:
* function name
* return values

### CODE REVIEW

**Comment by caspervdw** [comment]
@brendan-ward  I think we reached a consensus on the return value in https://github.com/pygeos/pygeos/issues/128

Looking at this draft PR, the work is almost done. What I think needs to be changed (functionally) is:

 - a `return_indices` argument that defaults to False (can be implemented on the Python level, just discard the second element)
 - Naming. the PostGIS equivalent is ` ST_Dump`. can we name this `dump`?

**Comment by brendan-ward** [comment]
Agreed on the use of `return_indices`.

Personally, I don't like `ST_Dump` or `dump`.  It is ambiguous and doesn't give much information about what the function actually does. In ArcGIS and geopandas this is called `explode`, and it seems similar in intent to `explode` in pandas.

Could we go with `explode` or `explode_parts` instead?

I also need to add support for `GeometryCollection` via recursion, unless we want to handle that in a future PR?

**Comment by jorisvandenbossche** [comment]
I agree on "dump" not being a clear name IMO (I know the analogy with PostGIS is generally nice, but here I would personally not follow it)

**Comment by jorisvandenbossche** [comment]
Also, I personally think we should consider doing functions like `PyGetParts` in cython (once you need to start dealing with python function arguments, things get a lot simpler in cython), xref https://github.com/pygeos/pygeos/issues/51

**Comment by brendan-ward** [comment]
Superseded by #197

**Pull request closed without merging**
