### PR TITLE
Add travis for different CPU archs

### PR DESCRIPTION
**Pull request by caspervdw**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Cool! 

* We will need to migrate the account to travis-ci.com (from .org), see the warning on the travis page
* As mentioned in https://github.com/pygeos/pygeos/issues/291#issuecomment-772305610, we might need to only run this nightly or on demand if we want to keep it within the free limits of Travis (or contact Travis to ask for more)

**Comment by caspervdw** [comment]
OK I migrated to travis-ci.com , switched off the PR and commit triggers, and configured a daily run.

Not sure how this migration will take effect though.

**Comment by jorisvandenbossche** [comment]
It's a bit unfortunate that Travis has no way to trigger a build on a PR on demand (AFAIK). 
For example for github actions, whether it runs for a PR or only nightly is coded inside the yml, so you can always activate it inside the PR where you want to check this by editing the yml file (and remove again before merging).

Eg for #293 we probably want to run the tests to ensure they pass with the patch.

**Comment by caspervdw** [comment]
The total build time is now about 4 minutes. The `--no-build-isolation` prevented a numpy build, which saves a lot of time.

The free credits are (if I understand it correctly) 1000 minutes/month , so we have about 250 builds per month. I think not enough to build on every PR, but we may switch build on every commit to master?

**Comment by jorisvandenbossche** [comment]
Yes, every commit on master certainly sounds good I think

**Pull request merged**
